### ISSUE TITLE
Doubts about the visualization schema identifier

### ISSUE THREAD

**Issue by ralienpp** [MaximilianRies/vd-m-a-5050#1]
`visualization.schema` contains an identifier that trips my JSON schema validator (I use https://horejsek.github.io/python-fastjsonschema).

It complains about this line, that it cannot follow the reference:
https://github.com/MaximilianRies/vd-m-a-5050/blob/65281962a2aefc18d220becb090880dfa55b9a9a/visualization.schema#L3

If the `$id` is removed or replaced with an actual URI - then everything is fine. I was wondering whether this is so by design, or if it was overlooked.

According to the [documentation](https://json-schema.org/understanding-json-schema/structuring.html#the-id-property), the best practice for `$id` is to set it to an absolute URI, because besides being an identifier, it is also used as a base for other URIs used throughout the schema.

Can you clarify this aspect?

**Comment by MaximilianRies** [comment]
Hello dear ralienpp,

I'm sorry for this issue. So far we haven't found a permanent home for this project, but we will find one soonish. Because of this we did not use true URIs and kept those placeholders. Honestly, I overlooked those, since my validator never complained.

Please feel free to remove those placeholder IDs and submit a pull request. Otherwise I will get those fixed in about 4 weeks the latest.

With kind regards,
Max

**Comment by ralienpp** [comment]
Thanks for the swift response. I created a pull request, but in any case I am staying tuned for the next iteration of the standard and the accompanying schemas.

**Comment by MaximilianRies** [comment]
We will announce the new home for the JSON schemas and the next iteration of the standard in this repository for sure, so you can move over and contribute there.

Thanks for your pull request, I already merged it.

With kind regards,
Max
